
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author josue
 */
public class Launcher extends javax.swing.JFrame {
    
    /**
     * Creates new form Launcher
     */
    private Connection cn=null;
    private ResultSet rs=null;
    private Statement st=null;
    private DefaultTableModel model;
    public Launcher() {
        initComponents();
        conexion();
        actualizaFilm();
        actualizaSala();
        actualizaHorario();
        actualizaProyeccion();
        /*
        Detecta un cambio de pestaña y ejecuta una accion
        */
        jTabbedPane1.addChangeListener(new ChangeListener() {
        public void stateChanged(ChangeEvent e) {
            System.out.println(""+jTabbedPane1.getSelectedIndex());
            if(jTabbedPane1.getSelectedIndex()==4) //Index starts at 0, so Index 2 = Tab3
            {
                try{     
                    st=cn.createStatement();
                    st.executeQuery("SELECT id_film FROM Funciones.T_Film ORDER BY id_film");
                    rs = st.getResultSet();
                    jComboBoxNombreHorario.removeAllItems();
                    while(rs.next()){
                       String c = rs.getString("id_film");
                       jComboBoxNombreHorario.addItem(c);
                    }
                }catch(Exception err){
                    System.out.println(err);
                }
            }
            if(jTabbedPane1.getSelectedIndex()==2) //Index starts at 0, so Index 2 = Tab3
            {
                try{     
                    st=cn.createStatement();
                    st.executeQuery("SELECT id_sala FROM Funciones.T_Sala ORDER BY id_sala");
                    rs = st.getResultSet();
                    jComboBoxNumeroProyeccion.removeAllItems();
                    while(rs.next()){
                       String c = rs.getString("id_sala");
                       jComboBoxNumeroProyeccion.addItem(c);
                    }
                    st.executeQuery("SELECT id_horario FROM Funciones.T_Horario ORDER BY id_horario");
                    rs = st.getResultSet();
                    jComboBoxHorarioProyeccion.removeAllItems();
                    while(rs.next()){
                       String c = rs.getString("id_horario");
                       jComboBoxHorarioProyeccion.addItem(c);
                    }
                }catch(Exception err){
                    System.out.println(err);
                }
            }
        }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableProyeccion = new javax.swing.JTable();
        jComboBoxNumeroProyeccion = new javax.swing.JComboBox<>();
        jComboBoxHorarioProyeccion = new javax.swing.JComboBox<>();
        jButtonInsertaProyeccion = new javax.swing.JButton();
        jButtonModificaProyeccion = new javax.swing.JButton();
        jButtonEliminaProyeccion = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombreFilm = new javax.swing.JTextField();
        jTextFieldDuracionFilm = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFilm = new javax.swing.JTable();
        jButtonInsertaFilm = new javax.swing.JButton();
        jButtonModificaFilm = new javax.swing.JButton();
        jButtonEliminaFilm = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableHorario = new javax.swing.JTable();
        jTextFieldHoraHorario = new javax.swing.JTextField();
        jComboBoxNombreHorario = new javax.swing.JComboBox<>();
        jButtonInsertaHorario = new javax.swing.JButton();
        jButtonModificaHorario = new javax.swing.JButton();
        jButtonEliminaHorario = new javax.swing.JButton();
        jDateChooserHorario = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNumeroSala = new javax.swing.JTextField();
        jTextFieldCupoSala = new javax.swing.JTextField();
        jComboBoxTipoSala = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSala = new javax.swing.JTable();
        jButtonInsertarSala = new javax.swing.JButton();
        jButtonModificarSala = new javax.swing.JButton();
        jButtonEliminarSala = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1200, 800));

        jTabbedPane1.setToolTipText("");
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 791, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Detalle de venta", jPanel1);
        jPanel1.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 791, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Venta", jPanel2);

        jLabel9.setText("N° de Sala:");

        jLabel10.setText("Horarios:");

        jTableProyeccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableProyeccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProyeccionMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableProyeccion);

        jComboBoxNumeroProyeccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        jComboBoxHorarioProyeccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        jButtonInsertaProyeccion.setText("Insertar");
        jButtonInsertaProyeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertaProyeccionActionPerformed(evt);
            }
        });

        jButtonModificaProyeccion.setText("Modificar");

        jButtonEliminaProyeccion.setText("Eliminar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(31, 31, 31)
                                .addComponent(jComboBoxNumeroProyeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(44, 44, 44)
                                .addComponent(jComboBoxHorarioProyeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonInsertaProyeccion)
                        .addGap(45, 45, 45)
                        .addComponent(jButtonModificaProyeccion)
                        .addGap(45, 45, 45)
                        .addComponent(jButtonEliminaProyeccion)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxNumeroProyeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInsertaProyeccion)
                    .addComponent(jButtonModificaProyeccion)
                    .addComponent(jButtonEliminaProyeccion))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBoxHorarioProyeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Proyección", jPanel3);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Duración:");

        jTableFilm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableFilm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFilmMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableFilm);

        jButtonInsertaFilm.setText("Insertar");
        jButtonInsertaFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertaFilmActionPerformed(evt);
            }
        });

        jButtonModificaFilm.setText("Modificar");
        jButtonModificaFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificaFilmActionPerformed(evt);
            }
        });

        jButtonEliminaFilm.setText("Eliminar");
        jButtonEliminaFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminaFilmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldDuracionFilm, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(jTextFieldNombreFilm))
                        .addGap(31, 31, 31)
                        .addComponent(jButtonInsertaFilm)
                        .addGap(45, 45, 45)
                        .addComponent(jButtonModificaFilm)
                        .addGap(45, 45, 45)
                        .addComponent(jButtonEliminaFilm)))
                .addGap(117, 117, 117))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNombreFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInsertaFilm)
                    .addComponent(jButtonModificaFilm)
                    .addComponent(jButtonEliminaFilm))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldDuracionFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );

        jTabbedPane1.addTab("Film", jPanel5);

        jPanel6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel6FocusGained(evt);
            }
        });

        jLabel6.setText("Nombre:");

        jLabel7.setText("Fecha:");

        jLabel8.setText("Hora:");

        jTableHorario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableHorario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableHorarioMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableHorario);

        jComboBoxNombreHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        jButtonInsertaHorario.setText("Insertar");
        jButtonInsertaHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertaHorarioActionPerformed(evt);
            }
        });

        jButtonModificaHorario.setText("Modificar");
        jButtonModificaHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificaHorarioActionPerformed(evt);
            }
        });

        jButtonEliminaHorario.setText("Eliminar");
        jButtonEliminaHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminaHorarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldHoraHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jComboBoxNombreHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(131, 131, 131)
                                .addComponent(jButtonInsertaHorario)
                                .addGap(45, 45, 45)
                                .addComponent(jButtonModificaHorario)
                                .addGap(45, 45, 45)
                                .addComponent(jButtonEliminaHorario))
                            .addComponent(jDateChooserHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxNombreHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInsertaHorario)
                    .addComponent(jButtonModificaHorario)
                    .addComponent(jButtonEliminaHorario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jDateChooserHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldHoraHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Horario", jPanel6);

        jLabel3.setText("N° de Sala:");

        jLabel4.setText("Cupo:");

        jLabel5.setText("Tipo:");

        jComboBoxTipoSala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "3D", "4D"}));

        jTableSala.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableSala.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSalaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableSala);

        jButtonInsertarSala.setText("Insertar");
        jButtonInsertarSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarSalaActionPerformed(evt);
            }
        });

        jButtonModificarSala.setText("Modificar");
        jButtonModificarSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarSalaActionPerformed(evt);
            }
        });

        jButtonEliminarSala.setText("Eliminar");
        jButtonEliminarSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarSalaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCupoSala, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNumeroSala, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                .addComponent(jButtonInsertarSala)
                                .addGap(45, 45, 45)
                                .addComponent(jButtonModificarSala)
                                .addGap(45, 45, 45)
                                .addComponent(jButtonEliminarSala))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jComboBoxTipoSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(117, 117, 117))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNumeroSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInsertarSala)
                    .addComponent(jButtonModificarSala)
                    .addComponent(jButtonEliminarSala))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldCupoSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxTipoSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );

        jTabbedPane1.addTab("Sala", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizaFilm(){
        /*
        Actualiza la tabla
        */
        try{
            String renglon[][] = {};
            String columna[] = {"id_film","nombre_film","duracion"};
            String query="SELECT * FROM Funciones.T_Film";
            model = new DefaultTableModel(renglon,columna);
            jTableFilm.setModel(model);
            rs = st.executeQuery(query);
            Object tuplas[] = new Object[3];
            while(rs.next())
            {
                tuplas[0] = rs.getObject("id_film");
                tuplas[1] = rs.getObject("nombre_film");
                tuplas[2] = rs.getObject("duracion");
                model.addRow(tuplas);
                System.out.println(model.getRowCount());
            }
            
        }catch(Exception e){
            System.out.println("Error al cargar los datos");
        }
    }
    
    private void actualizaSala(){
        /*
        Actualiza la tabla
        */
        try{
            String renglon[][] = {};
            String columna[] = {"id_sala","num_sala","capacidad", "tipo_sala"};
            String query = "SELECT * FROM Funciones.T_Sala";
            model = new DefaultTableModel(renglon,columna);
            jTableSala.setModel(model);
            rs = st.executeQuery(query);
            Object tuplas[] = new Object[4];
            while(rs.next())
            {
                tuplas[0] = rs.getObject("id_sala");
                tuplas[1] = rs.getObject("num_sala");
                tuplas[2] = rs.getObject("capacidad");
                tuplas[3] = rs.getObject("tipo_sala");
                model.addRow(tuplas);
                System.out.println(model.getRowCount());
            }
            
        }catch(Exception e){
            System.out.println("Error al cargar los datos");
        }
    }
    
        private void actualizaHorario(){
        /*
        Actualiza la tabla
        */
        try{
            String renglon[][] = {};
            String columna[] = {"id_horario","id_film","hora", "fecha"};
            String query = "SELECT * FROM Funciones.T_Horario";
            model = new DefaultTableModel(renglon,columna);
            jTableHorario.setModel(model);
            rs = st.executeQuery(query);
            Object tuplas[] = new Object[4];
            while(rs.next())
            {
                tuplas[0] = rs.getObject("id_horario");
                tuplas[1] = rs.getObject("id_film");
                tuplas[2] = rs.getObject("hora");
                tuplas[3] = rs.getObject("fecha");
                model.addRow(tuplas);
                System.out.println(model.getRowCount());
            }
            
        }catch(Exception e){
            System.out.println("Error al cargar los datos");
        }
    }
    
    private void actualizaProyeccion(){
        /*
        Actualiza la tabla T_Proyeccion
        */
        try{
            String renglon[][] = {};
            String columna[] = {"id_proyeccion", "id_sala", "id_horario", "asientos_disponibles"};
            String query = "SELECT * FROM Funciones.T_Proyeccion";
            model = new DefaultTableModel(renglon,columna);
            jTableProyeccion.setModel(model);
            rs = st.executeQuery(query);
            Object tuplas[] = new Object[4];
            while(rs.next())
            {
                tuplas[0] = rs.getObject("id_proyeccion");
                tuplas[1] = rs.getObject("id_sala");
                tuplas[2] = rs.getObject("id_horario");
                tuplas[3] = rs.getObject("asientos_disponibles");
                model.addRow(tuplas);
                System.out.println(model.getRowCount());
            }
            
        }catch(Exception e){
            System.out.println("Error al cargar los datos");
        }
    }
        
    private void conexion(){
        try{
            String url = "jdbc:postgresql://localhost:5432/Cinema";
            String usuario = "postgres";
            String password = "12345";
            Class.forName("org.postgresql.Driver");
            cn=DriverManager.getConnection(url,usuario,password);
            st=cn.createStatement();
            if(cn!=null)
                System.out.println("Conexion establecida");
            
        }catch(Exception e)
        {
            System.out.println("Error de conexion");
        }
    }
    
    private void jButtonInsertaFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertaFilmActionPerformed
        /*
        *Inserta tupla en la tabla Film
        */
        try
        {
            st=cn.createStatement();
            String nomFilm = jTextFieldNombreFilm.getText();
            int duracion = Integer.parseInt(jTextFieldDuracionFilm.getText());
            String query = "INSERT INTO Funciones.T_Film(nombre_film,duracion) VALUES('" + nomFilm + "'," + duracion + ")";
            st.executeUpdate(query);
            //cn.commit();
            actualizaFilm();
            jTextFieldNombreFilm.setText("");
            jTextFieldDuracionFilm.setText("");
            System.out.println("Tupla insertada correctamente");
        }catch(Exception e)
        {
            System.out.println("Error al insertar");
        }
    }//GEN-LAST:event_jButtonInsertaFilmActionPerformed

    private void jTableFilmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFilmMouseClicked
        // TODO add your handling code here:
        jTextFieldNombreFilm.setText(jTableFilm.getValueAt(jTableFilm.getSelectedRow(), 1).toString());
        jTextFieldDuracionFilm.setText(jTableFilm.getValueAt(jTableFilm.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_jTableFilmMouseClicked

    private void jButtonModificaFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificaFilmActionPerformed
        /*
        Modifica la tabla T_Film
        */
        try
        {
            int id_film = Integer.parseInt(jTableFilm.getValueAt(jTableFilm.getSelectedRow(), 0).toString());
            st=cn.createStatement();
            String nomFilm = jTextFieldNombreFilm.getText();
            int duracion = Integer.parseInt(jTextFieldDuracionFilm.getText());
            String query = "UPDATE Funciones.T_Film SET nombre_film='" + nomFilm + "', duracion=" + duracion + "  WHERE id_film=" + id_film + ";";
            st.executeUpdate(query);
            //cn.commit();
            actualizaFilm();
            jTextFieldNombreFilm.setText("");
            jTextFieldDuracionFilm.setText("");
            System.out.println("Tupla modificada correctamente");
        }catch(Exception e)
        {
            System.out.println("Error al modificar");
        }
    }//GEN-LAST:event_jButtonModificaFilmActionPerformed

    private void jButtonEliminaFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminaFilmActionPerformed
        /*
        Elimina una tupla de la tabla T_Film
        */
        try
        {
            int id_film = Integer.parseInt(jTableFilm.getValueAt(jTableFilm.getSelectedRow(), 0).toString());
            st=cn.createStatement();
            String query = "DELETE FROM Funciones.T_Film WHERE id_film=" + id_film + ";";
            st.executeUpdate(query);
            //cn.commit();
            actualizaFilm();
            jTextFieldNombreFilm.setText("");
            jTextFieldDuracionFilm.setText("");
            System.out.println("Tupla eliminada correctamente");
        }catch(Exception e)
        {
            System.out.println("Error al eliminar");
        }
    }//GEN-LAST:event_jButtonEliminaFilmActionPerformed

    private void jTableSalaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSalaMouseClicked
        // TODO add your handling code here:
        jTextFieldNumeroSala.setText(jTableSala.getValueAt(jTableSala.getSelectedRow(), 1).toString());
        jTextFieldCupoSala.setText(jTableSala.getValueAt(jTableSala.getSelectedRow(), 2).toString());
        
        jComboBoxTipoSala.setSelectedItem(jTableSala.getValueAt(jTableSala.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_jTableSalaMouseClicked

    private void jButtonInsertarSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarSalaActionPerformed
        /*
        *Inserta tupla en la tabla Sala
        */
        try
        {
            st=cn.createStatement();
            int num_sala = Integer.parseInt(jTextFieldNumeroSala.getText());
            int cupo = Integer.parseInt(jTextFieldCupoSala.getText());
            String tipo = jComboBoxTipoSala.getSelectedItem().toString();
            String query = "INSERT INTO Funciones.T_Sala(num_sala,capacidad,tipo_sala) VALUES("+ num_sala + "," + cupo + ",'" + tipo +"')";
            st.executeUpdate(query);
            //cn.commit();
            actualizaSala();
            jTextFieldNumeroSala.setText("");
            jTextFieldCupoSala.setText("");
            System.out.println("Tupla insertada correctamente");
        }catch(Exception e)
        {
            System.out.println("Error al insertar");
        }
    }//GEN-LAST:event_jButtonInsertarSalaActionPerformed

    private void jButtonModificarSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarSalaActionPerformed
        /*
        Modifica la tabla T_Sala
        */
        try
        {
            int id_sala = Integer.parseInt(jTableSala.getValueAt(jTableSala.getSelectedRow(), 0).toString());
            st=cn.createStatement();
            int num_sala = Integer.parseInt(jTextFieldNumeroSala.getText());
            int capacidad = Integer.parseInt(jTextFieldCupoSala.getText());
            String tipo_sala = jComboBoxTipoSala.getSelectedItem().toString();
            String query = "UPDATE Funciones.T_Sala SET num_sala=" + num_sala + ", capacidad=" + capacidad + ", tipo_sala='" + tipo_sala +"'  WHERE id_sala=" + id_sala + ";";
            st.executeUpdate(query);
            //cn.commit();
            actualizaSala();
            jTextFieldNumeroSala.setText("");
            jTextFieldCupoSala.setText("");
            System.out.println("Tupla modificada correctamente");
        }catch(Exception e)
        {
            System.out.println("Error al modificar");
        }
    }//GEN-LAST:event_jButtonModificarSalaActionPerformed

    private void jButtonEliminarSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarSalaActionPerformed
        /*
        Elimina una tupla de la tabla T_Sala
        */
        try
        {
            int id_sala = Integer.parseInt(jTableSala.getValueAt(jTableSala.getSelectedRow(), 0).toString());
            st=cn.createStatement();
            String query = "DELETE FROM Funciones.T_Sala WHERE id_sala=" + id_sala + ";";
            st.executeUpdate(query);
            //cn.commit();
            actualizaSala();
            jTextFieldNumeroSala.setText("");
            jTextFieldCupoSala.setText("");
            System.out.println("Tupla eliminada correctamente");
        }catch(Exception e)
        {
            System.out.println("Error al eliminar");
        }
    }//GEN-LAST:event_jButtonEliminarSalaActionPerformed

    private void jTableHorarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableHorarioMouseClicked
        jTextFieldHoraHorario.setText(jTableHorario.getValueAt(jTableHorario.getSelectedRow(), 2).toString());
        jComboBoxNombreHorario.setSelectedItem(jTableHorario.getValueAt(jTableHorario.getSelectedRow(), 1).toString());
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String fecha = sdf.format(jTableHorario.getValueAt(jTableHorario.getSelectedRow(), 3));
        java.util.Date date;
        try {
            date = sdf.parse(fecha);
            jDateChooserHorario.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(Launcher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTableHorarioMouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jPanel6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel6FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6FocusGained

    private void jButtonInsertaHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertaHorarioActionPerformed
        /*
        *Inserta tupla en la tabla Horario
        */
        try
        {
            st=cn.createStatement();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String fecha = sdf.format(jDateChooserHorario.getDate());
            int id_film = Integer.parseInt(jComboBoxNombreHorario.getSelectedItem().toString());
            String hora = jTextFieldHoraHorario.getText();
            String query = "INSERT INTO Funciones.T_Horario(id_film, hora, fecha) VALUES("+ id_film + ",'" + hora + "','" + fecha +"')";
            st.executeUpdate(query);
            actualizaHorario();
            jTextFieldHoraHorario.setText("");
            System.out.println("Tupla insertada correctamente");
        }catch(Exception e)
        {
            System.out.println("Error al insertar");
        }
    }//GEN-LAST:event_jButtonInsertaHorarioActionPerformed

    private void jButtonModificaHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificaHorarioActionPerformed
        /*
        Modifica tabla T_Horario
        */
        try
        {
            int id_horario = Integer.parseInt(jTableHorario.getValueAt(jTableHorario.getSelectedRow(), 0).toString());
            st=cn.createStatement();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String fecha = sdf.format(jDateChooserHorario.getDate());
            int id_film = Integer.parseInt(jComboBoxNombreHorario.getSelectedItem().toString());
            String hora = jTextFieldHoraHorario.getText();
            String query = "UPDATE Funciones.T_Horario SET id_film="+ id_film + ",hora='" + hora + "',fecha='" + fecha +"' WHERE id_horario=" + id_horario;
            st.executeUpdate(query);
            actualizaHorario();
            jTextFieldHoraHorario.setText("");
            System.out.println("Tupla modificada correctamente");
        }catch(Exception e)
        {
            System.out.println("Error al modificar");
        }
    }//GEN-LAST:event_jButtonModificaHorarioActionPerformed

    private void jButtonEliminaHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminaHorarioActionPerformed
        /*
        Elimina tabla T_Horario
        */
        try
        {
            int id_horario = Integer.parseInt(jTableHorario.getValueAt(jTableHorario.getSelectedRow(), 0).toString());
            st=cn.createStatement();
            String query = "DELETE FROM Funciones.T_Horario WHERE id_horario="+ id_horario;
            st.executeUpdate(query);
            actualizaHorario();
            jTextFieldHoraHorario.setText("");
            System.out.println("Tupla eliminada correctamente");
        }catch(Exception e)
        {
            System.out.println("Error al eliminar");
        }
    }//GEN-LAST:event_jButtonEliminaHorarioActionPerformed

    private void jButtonInsertaProyeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertaProyeccionActionPerformed
        /*
        *Inserta tupla en la tabla T_Proyeccion
        */
        try
        {
            st=cn.createStatement();
            int id_sala = Integer.parseInt(jComboBoxNumeroProyeccion.getSelectedItem().toString());
            int id_horario = Integer.parseInt(jComboBoxHorarioProyeccion.getSelectedItem().toString());
            String query = "INSERT INTO Funciones.T_Proyeccion(id_sala, id_horario, asientos_disponibles) VALUES("+ id_sala + "," + id_horario + "," + 0 +")";
            st.executeUpdate(query);
            actualizaProyeccion();
            System.out.println("Tupla insertada correctamente");
        }catch(Exception e)
        {
            System.out.println("Error al insertar");
        }
    }//GEN-LAST:event_jButtonInsertaProyeccionActionPerformed

    private void jTableProyeccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProyeccionMouseClicked
        jComboBoxNumeroProyeccion.setSelectedItem(jTableProyeccion.getValueAt(jTableProyeccion.getSelectedRow(), 1).toString());
        jComboBoxHorarioProyeccion.setSelectedItem(jTableProyeccion.getValueAt(jTableProyeccion.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_jTableProyeccionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Launcher().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEliminaFilm;
    private javax.swing.JButton jButtonEliminaHorario;
    private javax.swing.JButton jButtonEliminaProyeccion;
    private javax.swing.JButton jButtonEliminarSala;
    private javax.swing.JButton jButtonInsertaFilm;
    private javax.swing.JButton jButtonInsertaHorario;
    private javax.swing.JButton jButtonInsertaProyeccion;
    private javax.swing.JButton jButtonInsertarSala;
    private javax.swing.JButton jButtonModificaFilm;
    private javax.swing.JButton jButtonModificaHorario;
    private javax.swing.JButton jButtonModificaProyeccion;
    private javax.swing.JButton jButtonModificarSala;
    private javax.swing.JComboBox<String> jComboBoxHorarioProyeccion;
    private javax.swing.JComboBox<String> jComboBoxNombreHorario;
    private javax.swing.JComboBox<String> jComboBoxNumeroProyeccion;
    private javax.swing.JComboBox<String> jComboBoxTipoSala;
    private com.toedter.calendar.JDateChooser jDateChooserHorario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableFilm;
    private javax.swing.JTable jTableHorario;
    private javax.swing.JTable jTableProyeccion;
    private javax.swing.JTable jTableSala;
    private javax.swing.JTextField jTextFieldCupoSala;
    private javax.swing.JTextField jTextFieldDuracionFilm;
    private javax.swing.JTextField jTextFieldHoraHorario;
    private javax.swing.JTextField jTextFieldNombreFilm;
    private javax.swing.JTextField jTextFieldNumeroSala;
    // End of variables declaration//GEN-END:variables
}
